when:
  - event: push
    branch: main
  - event: tag

steps:
  - name: lint
    image: ruby:latest
    commands:
      - gem install rubocop
      - rubocop
    failure: ignore
  - name: build
    image: ruby:latest
    when:
      event: tag
    commands:
      - gem build disrb.gemspec
  - name: push
    image: ruby:latest
    when:
      event: tag
    environment:
      GEM_HOST_API_KEY:
        from_secret: rubygems_api_key
    commands:
      - gem push *.gem
  - name: release
    image: woodpeckerci/plugin-release
    when:
      event: tag
    settings:
      files:
        - '*.gem'
      api_key:
        from_secret: FORGEJO_ACCESS_TOKEN
