name: Rubocop

on:
  push:

jobs:
  rubocop:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Rubocop
        uses: hoovad/rubocop-action@v0.0.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}